return {
    ["defense_name"] = "",
    ["first_order"] = 1,
    ["version"] = 10300,
    ["attack_power"] = 154707,
    ["is_win"] = true,
    ["max_round_num"] = 10,
    ["defense_officer_level"] = 0,
    ["attack_hurt"] = 58174,
    ["defense_power"] = 0,
    ["waves"] = {
        [1] = {
            ["rounds"] = {
                [1] = {
                    ["attacks"] = {
                        [1] = {
                            ["attack_infos"] = {
                                [1] = {
                                    ["type"] = 1,
                                    ["is_live"] = true,
                                    ["value"] = 25000,
                                    ["defense_member"] = {
                                        ["member_info"] = 411,
                                        ["order_pos"] = 131076,
                                    },
                                },
                            },
                            ["skill_id"] = 2040020,
                            ["angers"] = {
                                [1] = {
                                    ["member"] = {
                                        ["member_info"] = 204,
                                        ["order_pos"] = 65537,
                                    },
                                    ["value"] = 4,
                                    ["type"] = 1,
                                    ["stype_and_show_type"] = 999,
                                    ["buff_id"] = 2102,
                                },
                            },
                            ["is_live"] = true,
                            ["type"] = 0,
                            ["attack_pos"] = {
                                ["member_info"] = 204,
                                ["order_pos"] = 65537,
                            },
                            ["attack_hero_info"] = 65740,
                            ["battle_effects"] = {
                                [1] = {
                                    ["member"] = {
                                        ["member_info"] = 204,
                                        ["order_pos"] = 65537,
                                    },
                                    ["skill_id"] = 2040020,
                                    ["value"] = 8000,
                                    ["type"] = 2,
                                    ["attack_member"] = {
                                        ["member_info"] = 204,
                                        ["order_pos"] = 65537,
                                    },
                                    ["pet_id"] = 204,
                                    ["buff_id"] = 2303,
                                },
                            },
                        },
                        [2] = {
						--[[
                            ["add_buffs"] = {
                                [1] = {
                                    ["new_id_and_remove_id"] = 65536,
                                    ["member"] = {
                                        ["member_info"] = 203,
                                        ["order_pos"] = 65539,
                                    },
                                    ["show_type"] = 3,
                                    ["round"] = 2,
                                    ["skill_id"] = 4110030,
                                    ["add_member"] = {
                                        ["member_info"] = 411,
                                        ["order_pos"] = 131076,
                                    },
                                    ["pet_id"] = 411,
                                    ["buff_id"] = 2202,
                                },
                            },
							--]]
                            ["attack_infos"] = {
                                [1] = {
                                    ["type"] = 1,
                                    ["is_live"] = true,
                                    ["value"] = 15000,
                                    ["defense_member"] = {
                                        ["member_info"] = 204,
                                        ["order_pos"] = 65537,
                                    },
                                },
                                [2] = {
                                    ["type"] = 1,
                                    ["is_live"] = true,
                                    ["value"] = 1500,
                                    ["defense_member"] = {
                                        ["member_info"] = 1,
                                        ["order_pos"] = 65541,
                                    },
                                },
                                [3] = {
                                    ["type"] = 1,
                                    ["is_live"] = true,
                                    ["value"] = 1500,
                                    ["defense_member"] = {
                                        ["member_info"] = 216,
                                        ["order_pos"] = 65542,
                                    },
                                },
                                [4] = {
                                    ["type"] = 1,
                                    ["is_live"] = true,
                                    ["value"] = 1500,
                                    ["defense_member"] = {
                                        ["member_info"] = 217,
                                        ["order_pos"] = 65540,
                                    },
                                },
                                [5] = {
                                    ["type"] = 1,
                                    ["is_live"] = true,
                                    ["value"] = 15000,
                                    ["defense_member"] = {
                                        ["member_info"] = 203,
                                        ["order_pos"] = 65539,
                                    },
                                },
                            },
                            ["angers"] = {
                                [1] = {
                                    ["member"] = {
                                        ["member_info"] = 411,
                                        ["order_pos"] = 131076,
                                    },
                                    ["value"] = 4,
                                    ["type"] = 1,
                                    ["stype_and_show_type"] = 999,
                                    ["buff_id"] = 2102,
                                },
                            },
                            ["is_live"] = true,
                            ["type"] = 0,
                            ["attack_pos"] = {
                                ["member_info"] = 411,
                                ["order_pos"] = 131076,
                            },
                            ["attack_hero_info"] = 131483,
                            ["skill_id"] = 4110030,
                        },
                        [3] = {
                            ["add_buffs"] = {
                                [1] = {
                                    ["new_id_and_remove_id"] = 131072,
                                    ["member"] = {
                                        ["member_info"] = 412,
                                        ["order_pos"] = 131078,
                                    },
                                    ["show_type"] = 3,
                                    ["round"] = 2,
                                    ["skill_id"] = 2030030,
                                    ["add_member"] = {
                                        ["member_info"] = 203,
                                        ["order_pos"] = 65539,
                                    },
                                    ["pet_id"] = 203,
                                    ["buff_id"] = 2203,
                                },
                            },
                            ["attack_infos"] = {
                                [1] = {
                                    ["value"] = 27000,
                                    ["type"] = 1,
									--[[
                                    ["awards"] = {
                                        [1] = {
                                            ["type"] = 6,
                                            ["size"] = 1,
                                            ["value"] = 3,
                                        },
                                    },
									--]]
                                    ["defense_member"] = {
                                        ["member_info"] = 411,
                                        ["order_pos"] = 131076,
                                    },
                                    ["is_live"] = false,
                                },
                                [2] = {
									--[[
                                    ["awards"] = {
                                        [1] = {
                                            ["type"] = 6,
                                            ["size"] = 2,
                                            ["value"] = 61,
                                        },
                                    },
									--]]
                                    ["value"] = 27000,
                                    ["type"] = 1,
                                    ["is_live"] = false,
									--[[
                                    ["hurt_infos"] = {
                                        [1] = {
                                            ["value"] = 0,
                                            ["id"] = 2,
                                        },
                                    },
									--]]
                                    ["defense_member"] = {
                                        ["member_info"] = 412,
                                        ["order_pos"] = 131078,
                                    },
                                },
                            },
                            ["angers"] = {
                                [1] = {
                                    ["member"] = {
                                        ["member_info"] = 203,
                                        ["order_pos"] = 65539,
                                    },
                                    ["value"] = 4,
                                    ["type"] = 1,
                                    ["stype_and_show_type"] = 999,
                                    ["buff_id"] = 2102,
                                },
                            },
                            ["is_live"] = true,
                            ["type"] = 0,
                            ["attack_pos"] = {
                                ["member_info"] = 203,
                                ["order_pos"] = 65539,
                            },
                            ["attack_hero_info"] = 65739,
                            ["skill_id"] = 2030030,
                        },
                    },
                    ["round_index"] = 1,
                },
            },
            ["members"] = {
                [1] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 1,
                    ["max_hp"] = 2500,
                    ["instrument_rank"] = 0,
                    ["hp"] = 2500,
                    ["camp"] = 1,
                    ["rank_lv"] = 0,
                    ["pos"] = 5,
                    ["anger"] = 2,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = true,
                    ["monster_id"] = 0,
                },
                [2] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 216,
                    ["max_hp"] = 2000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 2000,
                    ["camp"] = 1,
                    ["rank_lv"] = 0,
                    ["pos"] = 6,
                    ["anger"] = 2,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [3] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 217,
                    ["max_hp"] = 2000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 2000,
                    ["camp"] = 1,
                    ["rank_lv"] = 0,
                    ["pos"] = 4,
                    ["anger"] = 2,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [4] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 203,
                    ["max_hp"] = 35000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 35000,
                    ["camp"] = 1,
                    ["rank_lv"] = 0,
                    ["pos"] = 3,
                    ["anger"] = 4,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [5] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 204,
                    ["max_hp"] = 25000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 25000,
                    ["camp"] = 1,
                    ["rank_lv"] = 0,
                    ["pos"] = 1,
                    ["anger"] = 4,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [6] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 411,
                    ["max_hp"] = 50000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 50000,
                    ["camp"] = 2,
                    ["rank_lv"] = 0,
                    ["pos"] = 4,
                    ["anger"] = 4,
                    ["is_user"] = false,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 11001034,
                },
                [7] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 412,
                    ["max_hp"] = 24000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 24000,
                    ["camp"] = 2,
                    ["rank_lv"] = 0,
                    ["pos"] = 6,
                    ["anger"] = 4,
                    ["is_user"] = false,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 11001036,
                },
            },
            ["first_order"] = 1,
            ["members_final"] = {
                [1] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 1,
                    ["max_hp"] = 2500,
                    ["instrument_rank"] = 0,
                    ["hp"] = 1000,
                    ["camp"] = 1,
                    ["rank_lv"] = 0,
                    ["pos"] = 5,
                    ["anger"] = 2,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = true,
                    ["monster_id"] = 0,
                },
                [2] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 216,
                    ["max_hp"] = 2000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 500,
                    ["camp"] = 1,
                    ["rank_lv"] = 0,
                    ["pos"] = 6,
                    ["anger"] = 2,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [3] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 217,
                    ["max_hp"] = 2000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 500,
                    ["camp"] = 1,
                    ["rank_lv"] = 0,
                    ["pos"] = 4,
                    ["anger"] = 2,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [4] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 203,
                    ["max_hp"] = 35000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 20000,
                    ["camp"] = 1,
                    ["rank_lv"] = 0,
                    ["pos"] = 3,
                    ["anger"] = 0,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [5] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 204,
                    ["max_hp"] = 25000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 15000,
                    ["camp"] = 1,
                    ["rank_lv"] = 0,
                    ["pos"] = 1,
                    ["anger"] = 0,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
            },
        },
    },
    ["skill_ids"] = {
        [1] = 2040020,
        [2] = 4110030,
        [3] = 2030030,
    },
    ["attack_base_id"] = 1,
    ["attack_officer_level"] = 0,
    ["attack_name"] = "ww001",
    ["pk_type"] = 1,
    ["defense_base_id"] = 0,
}
