return {
    ["defense_name"] = "",
    ["first_order"] = 1,
    ["version"] = 10300,
    ["attack_power"] = 2602432,
    ["is_win"] = false,
    ["max_round_num"] = 10,
    ["defense_officer_level"] = 0,
    ["attack_hurt"] = 648763,
    ["defense_power"] = 0,
    ["waves"] = {
        [1] = {
            --开始进场的人物
            ["first_enter"] = {
                102, 104, 105, 106, 204, 205, 206, 
            },
            ["enter_stage"] = {
                [1] = { 202 },
            },
            ["rounds"] = {
                [1] = {
                    ["attacks"] = {
                        [1] = {
							--[[
                            ["add_buffs"] = {
                                [1] = {
                                    ["new_id_and_remove_id"] = 65536,
                                    ["member"] = {
                                        ["member_info"] = 201,
                                        ["order_pos"] = 65538,
                                    },
                                    ["show_type"] = 2,
                                    ["round"] = 7,
                                    ["skill_id"] = 2010030,
                                    ["add_member"] = {
                                        ["member_info"] = 201,
                                        ["order_pos"] = 65538,
                                    },
                                    ["pet_id"] = 201,
                                    ["buff_id"] = 2106,
                                },
                            },
							--]]
                            ["attack_infos"] = {
                                [1] = {
                                    ["value"] = 1800000,
                                    ["type"] = 1,
                                    ["is_live"] = true,
									--[[
                                    ["hurt_infos"] = {
                                        [1] = {
                                            ["value"] = 0,
                                            ["id"] = 2,
                                        },
                                    },
									--]]
                                    ["defense_member"] = {
                                        ["member_info"] = 403,
                                        ["order_pos"] = 131074,
                                    },
                                },
                                [2] = {
                                    ["type"] = 1,
                                    ["is_live"] = true,
                                    ["value"] = 1800000,
                                    ["defense_member"] = {
                                        ["member_info"] = 404,
                                        ["order_pos"] = 131077,
                                    },
                                },
                            },
                            ["angers"] = {
                                [1] = {
                                    ["member"] = {
                                        ["member_info"] = 201,
                                        ["order_pos"] = 65538,
                                    },
                                    ["value"] = 4,
                                    ["type"] = 1,
                                    ["stype_and_show_type"] = 999,
                                    ["buff_id"] = 2102,
                                },
                            },
                            ["is_live"] = true,
                            ["type"] = 0,
                            ["attack_pos"] = {
                                ["member_info"] = 201,
                                ["order_pos"] = 65538,
                            },
                            ["attack_hero_info"] = 65737,
                            ["skill_id"] = 2010030,
                        },
                        [2] = {
                            ["attack_infos"] = {
                                [1] = {
                                    ["type"] = 1,
                                    ["is_live"] = true,
                                    ["value"] = 1350000,
                                    ["defense_member"] = {
                                        ["member_info"] = 202,
                                        ["order_pos"] = 65541,
                                    },
                                },
                                [2] = {
                                    ["type"] = 1,
                                    ["is_live"] = true,
                                    ["value"] = 1350000,
                                    ["defense_member"] = {
                                        ["member_info"] = 301,
                                        ["order_pos"] = 65540,
                                    },
                                },
                                [3] = {
                                    ["type"] = 1,
                                    ["is_live"] = true,
                                    ["value"] = 4050000,
                                    ["defense_member"] = {
                                        ["member_info"] = 201,
                                        ["order_pos"] = 65538,
                                    },
                                },
                                [4] = {
                                    ["type"] = 1,
                                    ["is_live"] = true,
                                    ["value"] = 1350000,
                                    ["defense_member"] = {
                                        ["member_info"] = 302,
                                        ["order_pos"] = 65542,
                                    },
                                },
                            },
                            ["angers"] = {
                                [1] = {
                                    ["member"] = {
                                        ["member_info"] = 403,
                                        ["order_pos"] = 131074,
                                    },
                                    ["value"] = 4,
                                    ["type"] = 1,
                                    ["stype_and_show_type"] = 999,
                                    ["buff_id"] = 2102,
                                },
                            },
                            ["is_live"] = true,
                            ["type"] = 0,
                            ["attack_pos"] = {
                                ["member_info"] = 403,
                                ["order_pos"] = 131074,
                            },
                            ["attack_hero_info"] = 131475,
                            ["skill_id"] = 4030030,
                        },
                        [3] = {
                            ["attack_infos"] = {
                                [1] = {
                                    ["type"] = 1,
                                    ["is_live"] = true,
                                    ["value"] = 1400000,
                                    ["defense_member"] = {
                                        ["member_info"] = 401,
                                        ["order_pos"] = 131076,
                                    },
                                },
                                [2] = {
                                    ["type"] = 1,
                                    ["is_live"] = true,
                                    ["value"] = 1400000,
                                    ["defense_member"] = {
                                        ["member_info"] = 404,
                                        ["order_pos"] = 131077,
                                    },
                                },
                                [3] = {
                                    ["type"] = 1,
                                    ["is_live"] = true,
                                    ["value"] = 1400000,
                                    ["defense_member"] = {
                                        ["member_info"] = 402,
                                        ["order_pos"] = 131078,
                                    },
                                },
                            },
                            ["angers"] = {
                                [1] = {
                                    ["member"] = {
                                        ["member_info"] = 301,
                                        ["order_pos"] = 65540,
                                    },
                                    ["value"] = 4,
                                    ["type"] = 1,
                                    ["stype_and_show_type"] = 999,
                                    ["buff_id"] = 2102,
                                },
                            },
                            ["is_live"] = true,
                            ["type"] = 0,
                            ["attack_pos"] = {
                                ["member_info"] = 301,
                                ["order_pos"] = 65540,
                            },
                            ["attack_hero_info"] = 65837,
                            ["skill_id"] = 3010030,
                        },
                        [4] = {
                            ["attack_infos"] = {
                                [1] = {
                                    ["type"] = 1,
                                    ["is_live"] = true,
                                    ["value"] = 5600000,
                                    ["defense_member"] = {
                                        ["member_info"] = 201,
                                        ["order_pos"] = 65538,
                                    },
                                },
                            },
                            ["angers"] = {
                                [1] = {
                                    ["member"] = {
                                        ["member_info"] = 401,
                                        ["order_pos"] = 131076,
                                    },
                                    ["value"] = 4,
                                    ["type"] = 1,
                                    ["stype_and_show_type"] = 999,
                                    ["buff_id"] = 2102,
                                },
                                [2] = {
                                    ["member"] = {
                                        ["member_info"] = 401,
                                        ["order_pos"] = 131076,
                                    },
                                    ["value"] = 2,
                                    ["type"] = 2,
                                    ["stype_and_show_type"] = 4,
                                    ["buff_id"] = 2108,
                                },
                            },
                            ["is_live"] = true,
                            ["type"] = 0,
                            ["attack_pos"] = {
                                ["member_info"] = 401,
                                ["order_pos"] = 131076,
                            },
                            ["attack_hero_info"] = 131473,
                            ["skill_id"] = 4010030,
                        },

                    },
                    ["round_index"] = 1,
                },
},
            ["members"] = {
                [1] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 202,
                    ["max_hp"] = 1600000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 1600000,
                    ["camp"] = 1,
                    ["rank_lv"] = 0,
                    ["pos"] = 5,
                    ["anger"] = 4,
                    ["is_user"] = false,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [2] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 301,
                    ["max_hp"] = 1600000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 1600000,
                    ["camp"] = 1,
                    ["rank_lv"] = 0,
                    ["pos"] = 4,
                    ["anger"] = 4,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [3] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 201,
                    ["max_hp"] = 10550000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 10550000,
                    ["camp"] = 1,
                    ["rank_lv"] = 0,
                    ["pos"] = 2,
                    ["anger"] = 4,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [4] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 302,
                    ["max_hp"] = 1600000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 1600000,
                    ["camp"] = 1,
                    ["rank_lv"] = 0,
                    ["pos"] = 6,
                    ["anger"] = 4,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [5] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 402,
                    ["max_hp"] = 2350000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 2350000,
                    ["camp"] = 2,
                    ["rank_lv"] = 0,
                    ["pos"] = 6,
                    ["anger"] = 4,
                    ["is_user"] = false,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [6] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 403,
                    ["max_hp"] = 4000000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 4000000,
                    ["camp"] = 2,
                    ["rank_lv"] = 0,
                    ["pos"] = 2,
                    ["anger"] = 4,
                    ["is_user"] = false,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [7] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 401,
                    ["max_hp"] = 2350000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 2350000,
                    ["camp"] = 2,
                    ["rank_lv"] = 0,
                    ["pos"] = 4,
                    ["anger"] = 4,
                    ["is_user"] = false,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [8] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 404,
                    ["max_hp"] = 4200000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 4200000,
                    ["camp"] = 2,
                    ["rank_lv"] = 0,
                    ["pos"] = 5,
                    ["anger"] = 4,
                    ["is_user"] = false,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
            },
            ["first_order"] = 1,
            ["members_final"] = {
                [1] = {
                    ["knight_id"] = 405,
                    ["max_hp"] = 4453,
                    ["instrument_rank"] = 0,
                    ["hp"] = 4453,
                    ["camp"] = 2,
                    ["rank_lv"] = 0,
                    ["anger"] = 0,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["pos"] = 4,
                    ["monster_id"] = 0,
                },
                [2] = {
                    ["knight_id"] = 403,
                    ["max_hp"] = 9896,
                    ["instrument_rank"] = 0,
                    ["hp"] = 9896,
                    ["camp"] = 2,
                    ["rank_lv"] = 0,
                    ["anger"] = 0,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["pos"] = 5,
                    ["monster_id"] = 0,
                },
                [3] = {
                    ["knight_id"] = 406,
                    ["max_hp"] = 8500000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 500000,
                    ["camp"] = 2,
                    ["rank_lv"] = 0,
                    ["anger"] = 4,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["pos"] = 6,
                    ["monster_id"] = 0,
                },
				[4] = {
                    ["knight_id"] = 406,
                    ["max_hp"] = 8500000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 500000,
                    ["camp"] = 2,
                    ["rank_lv"] = 0,
                    ["anger"] = 4,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["pos"] = 6,
                    ["monster_id"] = 0,
                },
            },
        },
    },
	["skill_ids"] = {
        [1] = 2010030,--赵云合击
        [2] = 4030030,--吕布合击
        [3] = 3010030,--孙策合击
        [4] = 4010030,--左慈合击
    },
    ["attack_base_id"] = 202,
    ["attack_officer_level"] = 0,
    ["attack_name"] = "ww001",
    ["pk_type"] = 1,
    ["defense_base_id"] = 0,
}
