return {
    ["defense_name"] = "",
    ["first_order"] = 1,
    ["version"] = 10300,
    ["attack_power"] = 157742,
    ["is_win"] = true,
    ["max_round_num"] = 10,
    ["defense_officer_level"] = 0,
    ["attack_hurt"] = 102764,
    ["defense_power"] = 0,
    ["waves"] = {
        [1] = {
            ["rounds"] = {
                [1] = {
                    ["attacks"] = {
                        [1] = {
                            ["attack_infos"] = {
                                [1] = {
                                    ["value"] = 11000,
                                    ["type"] = 1,
                                    --[[
									["awards"] = {
                                        [1] = {
                                            ["type"] = 6,
                                            ["size"] = 2,
                                            ["value"] = 61,
                                        },
                                    },
									--]]
                                    ["defense_member"] = {
                                        ["member_info"] = 431,
                                        ["order_pos"] = 131073,
                                    },
                                    ["is_live"] = false,
                                },
                            },
                            ["skill_id"] = 4040020,
                            ["angers"] = {
                                [1] = {
                                    ["member"] = {
                                        ["member_info"] = 404,
                                        ["order_pos"] = 65537,
                                    },
                                    ["value"] = 4,
                                    ["type"] = 1,
                                    ["stype_and_show_type"] = 999,
                                    ["buff_id"] = 2102,
                                },
                            },
                            ["is_live"] = true,
                            ["type"] = 0,
                            ["attack_pos"] = {
                                ["member_info"] = 404,
                                ["order_pos"] = 65537,
                            },
                            ["attack_hero_info"] = 65940,
                            ["battle_effects"] = {
                                [1] = {
                                    ["member"] = {
                                        ["member_info"] = 404,
                                        ["order_pos"] = 65537,
                                    },
                                    ["skill_id"] = 4040020,
                                    ["value"] = 5500,
                                    ["type"] = 2,
                                    ["attack_member"] = {
                                        ["member_info"] = 404,
                                        ["order_pos"] = 65537,
                                    },
                                    ["pet_id"] = 404,
                                    ["buff_id"] = 2303,
                                },
                            },
                        },
                        [2] = {
							
                            ["add_buffs"] = {
                                [1] = {
                                    ["new_id_and_remove_id"] = 65536,
                                    ["member"] = {
                                        ["member_info"] = 405,
                                        ["order_pos"] = 131074,
                                    },
                                    ["show_type"] = 2,
                                    ["round"] = 1,
                                    ["skill_id"] = 4050030,
                                    ["add_member"] = {
                                        ["member_info"] = 405,
                                        ["order_pos"] = 131074,
                                    },
                                    ["pet_id"] = 405,
                                    ["buff_id"] = 2105,
                                },
                            },
							
                            ["attack_infos"] = {
                                [1] = {
                                    ["value"] = 16000,
                                    ["type"] = 1,
                                    ["is_live"] = true,
                                    ["hurt_infos"] = {
                                        [1] = {
                                            ["value"] = 0,
                                            ["id"] = 2,
                                        },
                                    },
                                    ["defense_member"] = {
                                        ["member_info"] = 404,
                                        ["order_pos"] = 65537,
                                    },
                                },
                            },
                            ["angers"] = {
                                [1] = {
                                    ["member"] = {
                                        ["member_info"] = 405,
                                        ["order_pos"] = 131074,
                                    },
                                    ["value"] = 4,
                                    ["type"] = 1,
                                    ["stype_and_show_type"] = 999,
                                    ["buff_id"] = 2102,
                                },
                            },
                            ["is_live"] = true,
                            ["type"] = 0,
                            ["attack_pos"] = {
                                ["member_info"] = 405,
                                ["order_pos"] = 131074,
                            },
                            ["attack_hero_info"] = 131477,
                            ["skill_id"] = 4050030,
                        },
                        [3] = {
							--[[
                            ["add_buffs"] = {
                                [1] = {
                                    ["new_id_and_remove_id"] = 131072,
                                    ["member"] = {
                                        ["member_info"] = 403,
                                        ["order_pos"] = 65539,
                                    },
                                    ["show_type"] = 2,
                                    ["round"] = 99,
                                    ["skill_id"] = 4030030,
                                    ["add_member"] = {
                                        ["member_info"] = 403,
                                        ["order_pos"] = 65539,
                                    },
                                    ["pet_id"] = 403,
                                    ["buff_id"] = 2106,
                                },
                            },
							--]]
                            ["attack_infos"] = {
                                [1] = {
                                    ["value"] = 18000,
                                    ["type"] = 1,
									--[[
                                    ["awards"] = {
                                        [1] = {
                                            ["type"] = 6,
                                            ["size"] = 1,
                                            ["value"] = 3,
                                        },
                                    },
									--]]
                                    ["defense_member"] = {
                                        ["member_info"] = 6021,
                                        ["order_pos"] = 131078,
                                    },
                                    ["is_live"] = false,
                                },
                                [2] = {
                                    ["type"] = 1,
                                    ["is_live"] = false,
                                    ["value"] = 13500,
                                    ["defense_member"] = {
                                        ["member_info"] = 405,
                                        ["order_pos"] = 131074,
                                    },
                                },
                                [3] = {
                                    ["type"] = 1,
                                    ["is_live"] = false,
                                    ["value"] = 13500,
                                    ["defense_member"] = {
                                        ["member_info"] = 406,
                                        ["order_pos"] = 131075,
                                    },
                                },
                                [4] = {
                                    ["type"] = 1,
                                    ["is_live"] = false,
                                    ["value"] = 13500,
                                    ["defense_member"] = {
                                        ["member_info"] = 6021,
                                        ["order_pos"] = 131076,
                                    },
                                },
                                [5] = {
                                    ["type"] = 1,
                                    ["is_live"] = false,
                                    ["value"] = 18000,
                                    ["defense_member"] = {
                                        ["member_info"] = 6021,
                                        ["order_pos"] = 131077,
                                    },
                                },
                            },
                            ["angers"] = {
                                [1] = {
                                    ["member"] = {
                                        ["member_info"] = 403,
                                        ["order_pos"] = 65539,
                                    },
                                    ["value"] = 4,
                                    ["type"] = 1,
                                    ["stype_and_show_type"] = 999,
                                    ["buff_id"] = 2102,
                                },
                            },
                            ["is_live"] = true,
                            ["type"] = 0,
                            ["attack_pos"] = {
                                ["member_info"] = 403,
                                ["order_pos"] = 65539,
                            },
                            ["attack_hero_info"] = 65939,
                            ["skill_id"] = 4030030,
                        },
                    },
                    ["round_index"] = 1,
                },
            },
            ["members"] = {
                [1] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 217,
                    ["max_hp"] = 678,
                    ["instrument_rank"] = 0,
                    ["hp"] = 678,
                    ["camp"] = 1,
                    ["rank_lv"] = 0,
                    ["pos"] = 4,
                    ["anger"] = 2,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [2] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 403,
                    ["max_hp"] = 50000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 50000,
                    ["camp"] = 1,
                    ["rank_lv"] = 0,
                    ["pos"] = 3,
                    ["anger"] = 4,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [3] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 404,
                    ["max_hp"] = 30000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 30000,
                    ["camp"] = 1,
                    ["rank_lv"] = 0,
                    ["pos"] = 1,
                    ["anger"] = 4,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [4] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 1,
                    ["max_hp"] = 400,
                    ["instrument_rank"] = 0,
                    ["hp"] = 400,
                    ["camp"] = 1,
                    ["rank_lv"] = 1,
                    ["pos"] = 5,
                    ["anger"] = 2,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = true,
                    ["monster_id"] = 0,
                },
                [5] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 216,
                    ["max_hp"] = 250,
                    ["instrument_rank"] = 0,
                    ["hp"] = 250,
                    ["camp"] = 1,
                    ["rank_lv"] = 0,
                    ["pos"] = 6,
                    ["anger"] = 2,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [6] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 6021,
                    ["max_hp"] = 720,
                    ["instrument_rank"] = 0,
                    ["hp"] = 720,
                    ["camp"] = 2,
                    ["rank_lv"] = 0,
                    ["pos"] = 4,
                    ["anger"] = 4,
                    ["is_user"] = false,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [7] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 6021,
                    ["max_hp"] = 720,
                    ["instrument_rank"] = 0,
                    ["hp"] = 720,
                    ["camp"] = 2,
                    ["rank_lv"] = 0,
                    ["pos"] = 5,
                    ["anger"] = 4,
                    ["is_user"] = false,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [8] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 6021,
                    ["max_hp"] = 720,
                    ["instrument_rank"] = 0,
                    ["hp"] = 720,
                    ["camp"] = 2,
                    ["rank_lv"] = 0,
                    ["pos"] = 6,
                    ["anger"] = 4,
                    ["is_user"] = false,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [9] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 431,
                    ["max_hp"] = 10000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 10000,
                    ["camp"] = 2,
                    ["rank_lv"] = 0,
                    ["pos"] = 1,
                    ["anger"] = 4,
                    ["is_user"] = false,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [10] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 405,
                    ["max_hp"] = 12000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 12000,
                    ["camp"] = 2,
                    ["rank_lv"] = 0,
                    ["pos"] = 2,
                    ["anger"] = 4,
                    ["is_user"] = false,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [11] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 406,
                    ["max_hp"] = 12000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 12000,
                    ["camp"] = 2,
                    ["rank_lv"] = 0,
                    ["pos"] = 3,
                    ["anger"] = 4,
                    ["is_user"] = false,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
            },
            ["first_order"] = 1,
            ["members_final"] = {
                [1] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 1,
                    ["max_hp"] = 400,
                    ["instrument_rank"] = 0,
                    ["hp"] = 400,
                    ["camp"] = 1,
                    ["rank_lv"] = 1,
                    ["pos"] = 5,
                    ["anger"] = 2,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = true,
                    ["monster_id"] = 0,
                },
                [2] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 216,
                    ["max_hp"] = 250,
                    ["instrument_rank"] = 0,
                    ["hp"] = 250,
                    ["camp"] = 1,
                    ["rank_lv"] = 0,
                    ["pos"] = 6,
                    ["anger"] = 2,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [3] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 217,
                    ["max_hp"] = 678,
                    ["instrument_rank"] = 0,
                    ["hp"] = 678,
                    ["camp"] = 1,
                    ["rank_lv"] = 0,
                    ["pos"] = 4,
                    ["anger"] = 2,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [4] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 403,
                    ["max_hp"] = 50000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 35000,
                    ["camp"] = 1,
                    ["rank_lv"] = 0,
                    ["pos"] = 3,
                    ["anger"] = 0,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
                [5] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 404,
                    ["max_hp"] = 30000,
                    ["instrument_rank"] = 0,
                    ["hp"] = 14000,
                    ["camp"] = 1,
                    ["rank_lv"] = 0,
                    ["pos"] = 1,
                    ["anger"] = 0,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["monster_id"] = 0,
                },
            },
        },
    },
    ["skill_ids"] = {
        [1] = 4050030,
        [2] = 4030030,
        [3] = 4040020,
    },
    ["attack_base_id"] = 1,
    ["attack_officer_level"] = 0,
    ["attack_name"] = "ww001",
    ["pk_type"] = 1,
    ["defense_base_id"] = 0,
}
