export class TimelineType {
    public static rotate:number  =  0;
    0: "rotate";
    public static translate:number  =  1;
    1: "translate";
    public static scale:number  =  2;
    2: "scale";
    public static shear:number  =  3;
    3: "shear";
    public static attachment:number  =  4;
    4: "attachment";
    public static color:number  =  5;
    5: "color";
    public static deform:number  =  6;
    6: "deform";
    public static event:number  =  7;
    7: "event";
    public static drawOrder:number  =  8;
    8: "drawOrder";
    public static ikConstraint:number  =  9;
    9: "ikConstraint";
    public static transformConstraint:number  =  10;
    10: "transformConstraint";
    public static pathConstraintPosition:number  =  11;
    11: "pathConstraintPosition";
    public static pathConstraintSpacing:number  =  12;
    12: "pathConstraintSpacing";
    public static pathConstraintMix:number  =  13;
    13: "pathConstraintMix";
    public static twoColor:number  =  14;
    14: "twoColor";
}