--
cc.register("CommonButtonLargeHighlight", import(".CommonButtonHighLight"))
cc.register("CommonButtonLargeNormal", import(".CommonButtonNormal"))
-- cc.register("CommonButtonLargeNormal2", import(".CommonButtonNormal"))
cc.register("CommonButtonLargeNormal3", import(".CommonButtonNormal"))
cc.register("CommonButtonMediumHighlight", import(".CommonButtonHighLight"))
cc.register("CommonButtonMediumNormal", import(".CommonButtonNormal"))
-- cc.register("CommonButtonSmallHighlight", import(".CommonButtonNormal"))
cc.register("CommonButtonSmallNormal", import(".CommonButtonNormal"))
cc.register("CommonButtonSmallNormal2", import(".CommonButtonNormal"))
-- cc.register("CommonButtonMediumHighlight2", import(".CommonButtonNormal"))


cc.register("CommonButtonHighLight", import(".CommonButtonHighLight"))
cc.register("CommonButtonNormal", import(".CommonButtonNormal"))
cc.register("CommonButtonLevel1Highlight", import(".CommonButtonHighLight"))
cc.register("CommonButtonLevel1Normal", import(".CommonButtonNormal"))
cc.register("CommonButtonLevel2Highlight", import(".CommonButtonHighLight"))
cc.register("CommonButtonLevel2Normal", import(".CommonButtonNormal"))
cc.register("CommonButtonLevel3", import(".CommonButton"))
cc.register("CommonButtonSwitchLevel1", import(".CommonButtonSwitchLevel1"))
cc.register("CommonButtonSwitchLevel2", import(".CommonButtonSwitchLevel2"))
cc.register("CommonButtonLevel0Highlight", import(".CommonButtonHighLight"))
cc.register("CommonButtonLevel0Normal", import(".CommonButtonNormal"))
cc.register("CommonImageButtonLevel1Highlight", import(".CommonButtonHighLight"))

-- cc.register("CommonButtonLevel5Normal", import(".CommonButtonNormal"))
-- cc.register("CommonButtonLevel5Highlight", import(".CommonButtonHighLight"))

cc.register("CommonButtonDelete", import(".CommonButton"))
cc.register("CommonButtonSelect", import(".CommonButton"))
cc.register("CommonButtonTriggle", import(".CommonButtonNormal"))
cc.register("CommonButtonEdit", import(".CommonButton"))




-- cc.register("CommonButtonLevel4Normal", import(".CommonButtonNormal"))
cc.register("CommonButtonLevel4Highlight", import(".CommonButtonHighLight"))
cc.register("CommonButtonLevel5Highlight", import(".CommonButtonHighLight"))
cc.register("CommonButtonLevel5Normal", import(".CommonButtonNormal"))

cc.register("CommonButtonSwitchLevel0", import(".CommonButtonSwitchLevel0"))
cc.register("CommonButtonSwitchLevel5", import(".CommonButtonSwitchLevel5"))
cc.register("CommonButtonLevelPaimaiHightlight", import(".CommonButtonHighLight"))

cc.register("CommonTabGroupHorizon", import(".CommonTabGroup"))
cc.register("CommonTabGroupHorizon2", import(".CommonTabGroup"))
cc.register("CommonTabGroupHorizon3", import(".CommonTabGroup"))
cc.register("CommonTabGroupHorizon4", import(".CommonTabGroup"))
cc.register("CommonTabGroupHorizon5", import(".CommonTabGroup"))
cc.register("CommonTabGroupHorizon6", import(".CommonTabGroup"))
cc.register("CommonTabGroupHorizon8", import(".CommonTabGroup"))
cc.register("CommonTabGroupHorizon7", import(".CommonTabGroupHorizon7"))
cc.register("CommonTabGroupHorizon9", import(".CommonTabGroup"))
cc.register("CommonTabGroupVertical", import(".CommonTabGroup"))
cc.register("CommonTabGroupVertical2", import(".CommonTabGroup"))
cc.register("CommonTabGroupSmallHorizon", import(".CommonTabGroup"))
-- cc.register("CommonTabGroupBigHorizon", import(".CommonTabGroup"))
cc.register("CommonTabGroupScrollVertical", import(".CommonTabGroupScrollVertical"))
cc.register("CommonTabGroupScrollVertical2", import(".CommonTabGroupScrollVertical"))
cc.register("CommonTabGroupScrollHorizon", import(".CommonTabGroupScrollHorizon"))
cc.register("CommonTabGroupScrollHorizon2", import(".CommonTabGroupScrollHorizon"))
cc.register("CommonTabGroupHorizonClassify3",import(".CommonTabGroup"))
cc.register("CommonTabGroupHorizonClassify4",import(".CommonTabGroup"))
cc.register("CommonTabGroupTree", import(".CommonTabGroupTree"))

cc.register("CommonMainMenu", import(".CommonMainMenu"))
cc.register("CommonMainHeroNode", import(".CommonMainHeroNode"))

cc.register("CommonPopupSmall", import(".CommonPopupSmall"))
cc.register("CommonPopupNormal", import(".CommonPopupNormal"))
cc.register("CommonPopupNotice", import(".CommonPopupNotice"))
-- cc.register("CommonPopupBase", import(".CommonPopupSmall"))
-- cc.register("CommonNormalBuyPop", import(".CommonPopupSmall"))
-- cc.register("CommonNormalModifyNamePop", import(".CommonPopupSmall"))
-- cc.register("CommonPopupRank", import(".CommonPopupRank"))
-- cc.register("CommonTowerChoose", import(".CommonTowerChoose"))
cc.register("CommonSweep", import(".CommonSweep"))
cc.register("CommonSweepNode", import(".CommonSweepNode"))
-- cc.register("CommonPopupStageBG", import(".CommonPopupStageBG"))
cc.register("CommonPopupStageDetailBG", import(".CommonPopupStageDetailBG"))
-- cc.register("CommonExploreEventBG", import(".CommonExploreEventBG"))
cc.register("CommonTitle", import(".CommonTitle"))

--cc.register("CommonNormalMiniPopNoTitle", import(".CommonNormalMiniPopNoTitle"))
cc.register("CommonNormalSmallPop", import(".CommonNormalSmallPop"))
cc.register("CommonNormalSmallXSPop", import(".CommonNormalSmallPop"))
cc.register("CommonNormalSmallXXSPop", import(".CommonNormalSmallPop"))
cc.register("CommonNormalSmallMPop", import(".CommonNormalSmallPop"))
cc.register("CommonNormalMidPop", import(".CommonNormalSmallPop"))
cc.register("CommonNormalMiniPop", import(".CommonNormalSmallPop"))
cc.register("CommonNormalLargePop", import(".CommonNormalSmallPop"))
cc.register("CommonNormalMiniPop2", import(".CommonNormalSmallPop"))
cc.register("CommonNormalMiniPop3", import(".CommonNormalSmallPop"))
cc.register("CommonNormalMiniPop4", import(".CommonNormalSmallPop"))
cc.register("CommonNormalMiniPop5", import(".CommonNormalSmallPop"))
cc.register("CommonNormalMiniMaxPop", import(".CommonNormalSmallPop"))
-- cc.register("CommonNormalLargePop5", import(".CommonNormalSmallPop"))

cc.register("CommonNormalMidPop2", import(".CommonNormalSmallPop"))
-- cc.register("CommonNormalMidPop3", import(".CommonNormalSmallPop"))
-- cc.register("CommonNormalMidPop4", import(".CommonNormalSmallPop"))
cc.register("CommonNormalLargePop2", import(".CommonNormalSmallPop"))
cc.register("CommonNormalLargePop3", import(".CommonNormalSmallPop"))
-- cc.register("CommonNormalLargePop4", import(".CommonNormalSmallPop"))
cc.register("CommonNormalLargeWithChatPop", import(".CommonNormalSmallPop"))

cc.register("CommonDetailWindow", import(".CommonDetailWindow"))
cc.register("CommonHeroProperty", import(".CommonHeroProperty"))
cc.register("CommonPetProperty", import(".CommonPetProperty"))
cc.register("CommonEquipProperty", import(".CommonEquipProperty"))
cc.register("CommonJadeProperty", import(".CommonJadeProperty"))
cc.register("CommonTreasureProperty", import(".CommonTreasureProperty"))
cc.register("CommonInstrumentProperty", import(".CommonInstrumentProperty"))
cc.register("CommonAvatarProperty", import(".CommonAvatarProperty"))
cc.register("CommonHorseProperty", import(".CommonHorseProperty"))
cc.register("CommonHistoryWeaponProperty", import(".CommonHistoryWeaponProperty"))
cc.register("CommonNormalLargePop7", import(".CommonNormalSmallPop"))



cc.register("CommonTopbarBase", import(".CommonTopbarBase"))
cc.register("CommonTopBarItem", import(".CommonTopBarItem"))
cc.register("CommonTopbarItemList", import(".CommonTopbarItemList"))
cc.register("CommonActivityTopBarItem", import(".CommonTopBarItem"))
cc.register("CommonActivityTopbarItemList", import(".CommonTopbarItemList"))


cc.register("CommonButtonBack", import(".CommonButtonBack"))
cc.register("CommonButtonBackHome", import(".CommonButtonBackHome"))
cc.register("CommonShopItemCell", import(".CommonShopItemCell"))
cc.register("CommonShopItemCell2", import(".CommonShopItemCell2"))

cc.register("ListView", import(".CommonListView"))
cc.register("ScrollView", import(".CommonScrollView"))
cc.register("CommonGalleryView", import(".CommonGalleryView"))
cc.register("CommonScrollView2", import(".CommonScrollView2"))
cc.register("CommonListViewLineItem", import(".CommonListViewLineItem"))
cc.register("CommonListCellBase", import(".CommonListCellBase"))
cc.register("CommonListCellBase2", import(".CommonListCellBase"))


cc.register("CommonItemIcon", import(".CommonItemIcon"))
cc.register("CommonHeroIcon", import(".CommonHeroIcon"))
cc.register("CommonTacticsIcon", import(".CommonTacticsIcon"))
cc.register("CommonHistoryAvatar", import(".CommonHistoryAvatar"))
cc.register("CommonHistoryHeroName", import(".CommonHistoryHeroName"))
cc.register("CommonEquipIcon", import(".CommonEquipIcon"))
cc.register("CommonJadeIcon", import(".CommonJadeIcon"))
cc.register("CommonFlagIcon", import(".CommonFlagIcon"))
cc.register("CommonJadeAvatar", import(".CommonJadeAvatar"))
cc.register("CommonPetIcon", import(".CommonPetIcon"))
cc.register("CommonSilkbagIcon", import(".CommonSilkbagIcon"))
cc.register("CommonSilkbagAvatar", import(".CommonSilkbagAvatar"))
cc.register("CommonIconTemplate", import(".CommonIconTemplate"))
cc.register("CommonIconTemplateWithBg", import(".CommonIconTemplate"))

cc.register("CommonFragmentIcon", import(".CommonFragmentIcon"))
cc.register("CommonResourceIcon", import(".CommonResourceIcon"))
cc.register("CommonTreasureIcon", import(".CommonTreasureIcon"))
cc.register("CommonInstrumentIcon", import(".CommonInstrumentIcon"))
cc.register("CommonSelectNumNode", import(".CommonSelectNumNode"))
cc.register("CommonIconNameNode", import(".CommonIconNameNode"))
-- cc.register("CommonIconNameNoBgNode", import(".CommonIconNameNode"))


cc.register("CommonResourceInfo", import(".CommonResourceInfo"))
cc.register("CommonResourceInfoList", import(".CommonResourceInfoList"))
cc.register("CommonResourceInfoCost", import(".CommonResourceInfoCost"))
cc.register("CommonResourceInfoRefresh", import(".CommonResourceInfoRefresh"))

cc.register("CommonHeroAvatar", import(".CommonHeroAvatar"))
cc.register("CommonSimpleHeroAvatar", import(".CommonSimpleHeroAvatar"))

cc.register("CommonHeroName", import(".CommonHeroName"))
cc.register("CommonPlayerName", import(".CommonPlayerName"))
cc.register("CommonHeroName2", import(".CommonHeroName"))
cc.register("CommonPetVName", import(".CommonPetVName"))
cc.register("CommonPetMainAvatar", import(".CommonPetMainAvatar"))

cc.register("CommonContinueNode", import(".CommonContinueNode"))

cc.register("CommonShopResourceInfo", import(".CommonShopResourceInfo"))

cc.register("CommonEquipName", import(".CommonEquipName"))
-- cc.register("CommonEquipName2", import(".CommonEquipName"))
cc.register("CommonEquipAvatar", import(".CommonEquipAvatar"))
cc.register("CommonAttrDiff", import(".CommonAttrDiff"))
cc.register("CommonAttrDiff2", import(".CommonAttrDiff"))
cc.register("CommonHeroStar", import(".CommonStar"))
cc.register("CommonHeroStarBig", import(".CommonStar"))
cc.register("CommonLevelStar", import(".CommonStar"))
cc.register("CommonAttrNode", import(".CommonAttr"))
cc.register("CommonTreasureAvatar", import(".CommonTreasureAvatar"))
cc.register("CommonTreasureName", import(".CommonTreasureName"))
cc.register("CommonInstrumentAvatar", import(".CommonInstrumentAvatar"))
-- cc.register("CommonTreasureName2", import(".CommonTreasureName"))
cc.register("CommonInstrumentName", import(".CommonInstrumentName"))

cc.register("CommonCardFlip", import(".CommonCardFlip"))

cc.register("CommonPromptSilverNode", import(".CommonPromptSilverNode"))

cc.register("CommonPriceInfo", import(".CommonPriceInfo"))
cc.register("CommonPriceDiscountInfo", import(".CommonPriceInfo"))
cc.register("CommonPriceShowInfo", import(".CommonPriceInfo"))
cc.register("CommonPriceDiscountInfo2", import(".CommonPriceInfo"))
cc.register("CommonPriceShowInfo2", import(".CommonPriceInfo"))
cc.register("CommonPriceDiscountInfo3", import(".CommonPriceInfo"))
cc.register("CommonPriceShowInfo3", import(".CommonPriceInfo"))

cc.register("CommonRewardListNode", import(".CommonRewardListNode"))
cc.register("CommonRewardLogItem", import(".CommonRewardLogItem"))
cc.register("CommonItemListExchangeNode", import(".CommonItemListExchangeNode"))

cc.register("CommonDesValue", import(".CommonDesValue"))
cc.register("CommonDesDiff", import(".CommonDesDiff"))

cc.register("CommonFullScreen", import(".CommonFullScreen"))
cc.register("CommonFullScreenListView", import(".CommonFullScreenListView"))
-- cc.register("CommonFullScreen2", import(".CommonFullScreen"))
cc.register("CommonCheckBoxAnymoreHint", import(".CommonCheckBoxAnymoreHint"))
cc.register("CommonCheckBoxAnymoreHint1", import(".CommonCheckBoxAnymoreHint"))
cc.register("CommonFullScreenTitle", import(".CommonFullScreen"))
cc.register("CommonFullScreenTitleNoBg", import(".CommonFullScreen"))
cc.register("CommonFullScreenActivityTitle", import(".CommonFullScreen"))


cc.register("CommonDetailTitle", import(".CommonDetailTitle"))
cc.register("CommonDetailTitleWithBg", import(".CommonDetailTitle"))
cc.register("CommonDetailNewTitleWithBg", import(".CommonDetailTitle"))
cc.register("CommonHeroCountry", import(".CommonHeroCountry"))
cc.register("CommonHeroCountry2", import(".CommonHeroCountry2"))
cc.register("CommonHeroPower", import(".CommonHeroPower"))
cc.register("CommonTotalPower", import(".CommonHeroPower"))
cc.register("CommonHeroImage", import(".CommonHeroImage"))
cc.register("CommonHeroCountryFlag", import(".CommonHeroCountryFlag"))

cc.register("CommonPowerUpButton", import(".CommonPowerUpButton"))

cc.register("CommoRedPointNum", import(".CommoRedPointNum"))
cc.register("CommoRedPointNumBig", import(".CommoRedPointNum"))
cc.register("CommonPowerPrompt", import(".CommonPowerPrompt"))
-- cc.register("CommonPageTitle", import(".CommonPageTitle"))

cc.register("CommonVipInfo", import(".CommonVipInfo"))
cc.register("CommonSkillIcon", import(".CommonSkillIcon"))

cc.register("CommonPageViewIndicator", import(".CommonPageViewIndicator"))
cc.register("CommonPageViewIndicator2", import(".CommonPageViewIndicator"))
cc.register("CommonPageViewIndicator3", import(".CommonPageViewIndicator"))
cc.register("CommonProgressNode", import(".CommonProgressNode"))
cc.register("CommonProgressNodeSmall", import(".CommonProgressNode"))
cc.register("CommonTalkNode", import(".CommonTalkNode"))
cc.register("CommonTalkNode1", import(".CommonTalkNode"))
cc.register("CommonTalkNodeFamous", import(".CommonTalkNode"))
cc.register("CommonGuildTalk", import(".CommonGuildTalk"))

cc.register("CommonMiniChat", import(".CommonMiniChat"))
cc.register("ChatMiniNode", import(".CommonMiniChat"))
cc.register("ChatMiniNode1", import(".CommonMiniChat"))
-- cc.register("ChatMiniBossNode", import(".CommonMiniChat"))
cc.register("CommonChatMiniNode", import(".CommonMiniChat"))

cc.register("CommonSynthesisIcon", import(".CommonSynthesisIcon"))
cc.register("CommonMaterialIcon", import(".CommonMaterialIcon"))
cc.register("CommonGemstoneIcon", import(".CommonGemstoneIcon"))
cc.register("CommonCostNode", import(".CommonCostNode"))

cc.register("CommonPageView", import(".CommonPageView"))
cc.register("CommonPageItem", import(".CommonPageItem"))
cc.register("CommonPageItemHero", import(".CommonPageItem"))
cc.register("CommonPageItemSilkbag", import(".CommonPageItem"))

cc.register("CommonVerticalText", import(".CommonVerticalText"))
cc.register("CommonRollNumber", import(".CommonRollNumber"))
cc.register("CommonEmptyTipNode", import(".CommonEmptyTipNode"))
cc.register("CommonEmptyListNode", import(".CommonEmptyTipNode"))

cc.register("CommonHelp", import(".CommonHelp"))
cc.register("CommonHelpBig", import(".CommonHelp"))
cc.register("CommonDlgBackground", import(".CommonDlgBackground"))

cc.register("CommonRankIcon", import(".CommonRankIcon"))
cc.register("CommonStoryAvatar", import(".CommonStoryAvatar"))
cc.register("CommonStoryAvatar2", import(".CommonStoryAvatar2"))
cc.register("CommonTabIcon", import(".CommonTabIcon"))
cc.register("CommonTabIcon2", import(".CommonTabIcon2"))
cc.register("CommonTabIcon2_2", import(".CommonTabIcon2"))
cc.register("CommonMasterInfoNode", import(".CommonMasterInfoNode"))
cc.register("CommonButtonSwitchDraw", import(".CommonButtonSwitchDraw"))
cc.register("CommonVipNode", import(".CommonVipNode"))
cc.register("CommonLargeVipNode", import(".CommonVipImageNode"))
cc.register("CommonVipMidNode", import(".CommonVipImageNode"))
cc.register("CommonVoiceBtn", import(".CommonVoiceBtn"))

cc.register("CommonBox", import(".CommonBox"))
cc.register("CommonAvatarIcon", import(".CommonAvatarIcon"))
cc.register("CommonAvatarName", import(".CommonAvatarName"))
cc.register("CommonAvatarAvatar", import(".CommonAvatarAvatar"))


cc.register("CommonNextFunctionOpen", import(".CommonNextFunctionOpen"))
cc.register("CommonActivityCell", import(".CommonActivityCell"))
cc.register("CommonActivityCell", import(".CommonActivityCell"))
cc.register("CommonFightRecordNode", import(".CommonFightRecordNode"))
cc.register("GuildDungeonFightRecordNode", import(".CommonFightRecordNode"))

cc.register("CommonGuildFlag", import(".CommonGuildFlag"))
cc.register("CommonGuildFlagVertical", import(".CommonGuildFlagVertical"))
cc.register("CommonCountdown", import(".CommonCountdown")) 
cc.register("CommonCountdownAnimation", import(".CommonCountdownAnimation")) 
cc.register("CommonNormalSmallPop2", import(".CommonNormalSmallPop2")) 
cc.register("CommonGogok", import(".CommonGogok")) 

cc.register("CommonHorseIcon", import(".CommonHorseIcon")) 
cc.register("CommonHistoryHeroIcon", import(".CommonHistoryHeroIcon"))
cc.register("CommonHistoryWeaponIcon", import(".CommonHistoryWeaponIcon"))
cc.register("CommonHistoryWeaponAvatar", import(".CommonHistoryWeaponAvatar"))
cc.register("CommonAttrBook", import(".CommonAttrBook"))
cc.register("CommonHorseAvatar", import(".CommonHorseAvatar")) 
cc.register("CommonHorseName", import(".CommonHorseName")) 

cc.register("CommonColorProgress", import(".CommonColorProgress")) 
cc.register("CommonLoadingBar", import(".CommonLoadingBar")) 


cc.register("GroupsButton1", import(".CommonButton"))
cc.register("GroupsButton2", import(".CommonButtonCountDown"))
cc.register("GroupsButton3", import(".CommonButton"))
cc.register("CommonNormalSmallPop3", import(".CommonNormalSmallPop2")) 
cc.register("CommonButtonSelect2", import(".CommonButton"))
cc.register("CommonButtonDelete2", import(".CommonButtonCountDown"))
cc.register("CommonCheckBoxHintToRight", import(".CommonCheckBox"))

cc.register("CommonNumberSelectedItem", import(".CommonNumberSelectedItem"))
cc.register("CommonGroupsMiniList", import(".CommonGroupsMiniList"))
cc.register("CommonGroupsActiveTimeNode", import(".CommonGroupsActiveTimeNode"))

cc.register("CommonHorseEquipIcon",import(".CommonHorseEquipIcon"))
cc.register("CommonHorseEquipAvatar",import(".CommonHorseEquipAvatar"))
cc.register("CommonHorseEquipProperty", import(".CommonHorseEquipProperty"))
cc.register("CommonHorseEquipName",import(".CommonHorseEquipName"))

cc.register("CommonHeadFrame",import(".CommonHeadFrame"))
cc.register("CommonDefaultIcon",import(".CommonDefaultIcon"))
cc.register("CommonPointName",import(".CommonPointName"))

cc.register("CommonGoldenHeroName",import(".CommonGoldenHeroName"))
cc.register("CommonRechargeReward",import(".CommonRechargeReward"))
cc.register("CommonGrainCarAvatar",import(".CommonGrainCarAvatar"))
cc.register("CommonGrainCarIcon",import(".CommonGrainCarIcon"))

cc.register("CommonButtonAuction",import(".CommonButton"))

